name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Ejecutar el workflow cuando se haga push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar AWS CLI usando el Action oficial
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 4. Crear el archivo ZIP con el código de la Lambda
      - name: Zip the Lambda function
        run: zip -r Hello_World.zip Hello_World.py

      # 5. Subir el código a AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name HelloWorldLambda1 \
            --zip-file fileb://Hello_World.zip
